[project]
name = "url-shortener"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.128.0",
    "greenlet>=3.3.0",
    "pytest>=9.0.2",
    "sqlalchemy>=2.0.45",
]
